// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckBackendReady():Promise<boolean>;

export function GetGameDetails(arg1:number):Promise<main.GameDetailsView>;

export function GetGames(arg1:string,arg2:number,arg3:number):Promise<Array<main.GameView>>;

export function TriggerSync():Promise<void>;
