// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGameDetails(arg1) {
  return window['go']['main']['App']['GetGameDetails'](arg1);
}

export function GetGames(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetGames'](arg1, arg2, arg3);
}

export function TriggerSync() {
  return window['go']['main']['App']['TriggerSync']();
}

export function CheckBackendReady() {
  return window['go']['main']['App']['CheckBackendReady']();
}


